version: '3'

services:
  back-fun:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    command: npm run start
